---
name: test

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18', '20', '22' ]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup
        run: npm install

      - name: Run test
        run: | 
          npx playwright install-deps
          npx playwright install
          npm test 
          npx playwright test --browser=all